accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path


urlpatterns = [
    path("login/", LoginView.as_view(template_name="registration/login.html"), name="login"),
    path("logout/", LogoutView.as_view(template_name="registration/logged_out.html"), name="logout"),
]

app_name = "accounts"

restaurant/urls.py
from django.urls import path

from restaurant.views import (
    IndexView,
    CooksListView,
    CooksCreateView,
    CooksUpdateView,
    CookDetailView,
    CooksDeleteView,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    assign_cook_to_dish,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView
)


urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("cooks/", CooksListView.as_view(), name="cooks-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cooks-detail"),
    path("cooks/create/", CooksCreateView.as_view(), name="cooks-create"),
    path("cooks/<int:pk>/update/", CooksUpdateView.as_view(), name="cooks-update"),
    path("cooks/<int:pk>/delete/", CooksDeleteView.as_view(), name="cooks-delete"),
    path("dishes/", DishListView.as_view(), name="dishes-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path(
        "dishes/<int:pk>/toggle-assign/",
        assign_cook_to_dish,
        name="toggle-car-assign",
    ),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("dish-types/", DishTypeListView.as_view(), name="dish-types-list"),
    path("dish-types/create/", DishTypeCreateView.as_view(), name="dish-types-create"),
    path("dish-types/<int:pk>/update/", DishTypeUpdateView.as_view(), name="dish-types-update"),
    path("dish-types/<int:pk>/delete/", DishTypeDeleteView.as_view(), name="dish-types-delete"),
]

app_name = "restaurant"

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(null=True, blank=True, default=0)

    def __str__(self) -> str:
        return self.username

    def get_absolute_url(self) -> str:
        return reverse("restaurant:cooks-detail", kwargs={"pk": self.pk})

restaurant/models.py
from django.conf import settings
from django.db import models


class DishType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE, related_name="dishes")
    cooks = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="dishes")

    def __str__(self):
        return self.name

restaurant/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from accounts.models import Cook
from restaurant.models import Dish


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = (UserCreationForm.Meta.fields
                  + ("years_of_experience", "first_name", "last_name"))

    def clean_years_of_experience(self):
        return validate_years_of_experience(self.cleaned_data["years_of_experience"])


class CookUpdateForm(forms.ModelForm):
    class Meta:
        model = Cook
        fields = (UserCreationForm.Meta.fields
                  + ("years_of_experience", "first_name", "last_name"))

    def clean_years_of_experience(self):
        return validate_years_of_experience(self.cleaned_data["years_of_experience"])


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Dish
        fields = ["name", "description", "price", "dish_type", "cooks"]


class CookSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username"})
    )


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by name"
            }
        )
    )


class DishTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by name"
            }
        )
    )


def validate_years_of_experience(
    years_of_experience,
):
    if years_of_experience <= 0:
        raise ValidationError("Years of experience cannot be less than 1")
    elif years_of_experience > 55:
        raise ValidationError("Years of experience cannot be more than 55")

    return years_of_experience

restaurant/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from accounts.models import Cook
from restaurant.forms import (
    CookSearchForm,
    DishSearchForm,
    DishForm,
    CookCreationForm,
    CookUpdateForm,
    DishTypeSearchForm
)
from restaurant.mixins import SearchFormMixin
from restaurant.models import DishType, Dish


class IndexView(LoginRequiredMixin, generic.TemplateView):
    template_name = "restaurant/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({
            "num_cooks": Cook.objects.count(),
            "num_dishes_types": DishType.objects.count(),
            "num_dishes": Dish.objects.count(),
            "num_visits": self.request.session.get("num_visits", 0) + 1,
        })

        self.request.session["num_visits"] = context["num_visits"]

        return context


class CooksListView(LoginRequiredMixin, SearchFormMixin, generic.ListView):
    model = Cook
    template_name = "restaurant/cooks_list.html"
    paginate_by = 5
    search_form_class = CookSearchForm
    search_field_name = "username"


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    queryset = Cook.objects.prefetch_related("dishes__dish_type")
    template_name = "restaurant/cook_detail.html"


class CooksCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreationForm
    success_url = reverse_lazy("restaurant:cooks-list")
    template_name = "restaurant/cook_form.html"


class CooksUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookUpdateForm
    success_url = reverse_lazy("restaurant:cooks-list")
    template_name = "restaurant/cook_form.html"


class CooksDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("restaurant:cooks-list")
    template_name = "restaurant/cook_confirm_delete.html"


class DishListView(LoginRequiredMixin, SearchFormMixin, generic.ListView):
    model = Dish
    template_name = "restaurant/dishes_list.html"
    paginate_by = 5
    search_form_class = DishSearchForm
    search_field_name = "name"


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("restaurant:dishes-list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("restaurant:dishes-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("restaurant:dishes-list")


class DishTypeListView(LoginRequiredMixin, SearchFormMixin, generic.ListView):
    model = DishType
    template_name = "restaurant/dish_type_list.html"
    paginate_by = 5
    search_form_class = DishTypeSearchForm
    search_field_name = "name"


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = ["name", ]
    success_url = reverse_lazy("restaurant:dish-types-list")
    template_name = "restaurant/dish_form.html"


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = ["name",]
    template_name = "restaurant/dish_form.html"
    success_url = reverse_lazy("restaurant:dish-types-list")


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    success_url = reverse_lazy("restaurant:dish-types-list")
    template_name = "restaurant/dish_type_confirm_delete.html"


@login_required
def assign_cook_to_dish(request, pk):
    dish = get_object_or_404(Dish, id=pk)

    if not dish.cooks.filter(id=request.user.id).exists():
        dish.cooks.add(request.user)
    else:
        dish.cooks.remove(request.user)

    return redirect("restaurant:dish-detail", pk=pk)

templates/restaurant/cook_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container" style="margin-top: 20px">
  <h1>Delete cook {{ cook.first_name }} {{ cook.last_name }}({{ cook.username }})?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
  </div>
{% endblock %}

templates/restaurant/cook_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="container" style="margin-top: 20px">
    <h1>
      Username: {{ cook.username }}
      <a href="{% url 'restaurant:cooks-delete' pk=cook.id %}" class="btn btn-danger link-to-page">
        Delete
      </a>
      <a href="{% url 'restaurant:cooks-update' pk=cook.id %}" class="btn btn-primary link-to-page">
        Update cook
      </a>
    </h1>

    <p><strong>First name:</strong> {{ cook.first_name }}</p>
    <p><strong>Last name:</strong> {{ cook.last_name }}</p>
    <p><strong>Years of experience:</strong> {{ cook.years_of_experience }}</p>
    <p><strong>Is staff:</strong> {{ cook.is_staff }}</p>

    <div class="ml-3" style="margin-top: 20px;">
      <h3>Dishes</h3>

      {% for dish in cook.dishes.all %}
        <hr>
        <p><strong>Dish:</strong> {{ dish.name }}</p>
        <p><strong>Description:</strong> {{ dish.description }}</p>
        <p class="text-muted"><strong>Price:</strong> {{ dish.price }}</p>
        <p class="text-muted"><strong>Dish type:</strong> {{ dish.dish_type.name }}</p>

      {% empty %}
        <p>No dishes!</p>
      {% endfor %}
    </div>
  </div>
{% endblock %}

templates/restaurant/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container" style="margin-top: 20px">
    <h1>{{ object|yesno:"Update,Create" }} cook</h1>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}

      <input type="submit" value="Submit" class="btn btn-primary">
    </form>
  </div>
{% endblock %}

templates/restaurant/cooker_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="container" style="margin-top: 20px">
    <h1>
      Username: {{ cook.username }}
      <a href="{% url 'restaurant:cookers-delete' pk=cook.id %}" class="btn btn-danger link-to-page">
        Delete
      </a>
      <a href="{% url 'restaurant:cookers-update' pk=cook.id %}" class="btn btn-primary link-to-page">
        Update cook
      </a>
    </h1>

    <p><strong>First name:</strong> {{ cook.first_name }}</p>
    <p><strong>Last name:</strong> {{ cook.last_name }}</p>
    <p><strong>Years of experience:</strong> {{ cook.years_of_experience }}</p>
    <p><strong>Is staff:</strong> {{ cook.is_staff }}</p>

    <div class="ml-3" style="margin-top: 20px;">
      <h3>Dishes</h3>

      {% for dish in cook.dishes.all %}
        <hr>
        <p><strong>Dish:</strong> {{ dish.name }}</p>
        <p><strong>Description:</strong> {{ dish.description }}</p>
        <p class="text-muted"><strong>Price:</strong> {{ dish.price }}</p>
        <p class="text-muted"><strong>Dish type:</strong> {{ dish.dish_type.name }}</p>

      {% empty %}
        <p>No dishes!</p>
      {% endfor %}
    </div>
  </div>
{% endblock %}

templates/restaurant/cooks_list.html
{#{% extends "base.html" %}#}
{#{% load crispy_forms_filters %}#}
{##}
{#{% block content %}#}
{#  <h1>Cook List#}
{#    <a href="{% url 'restaurant:cookers-create' %}" class="btn btn-primary link-to-page">#}
{#      Create#}
{#    </a>#}
{#  </h1>#}
{#  #}
{#  <form method="get" action="" class="form-inline">#}
{#    {{ search_form|crispy }}#}
{#    <input type="submit" class="btn" style="border: 1px solid gray;" value="🔍">#}
{#  </form>#}
{##}
{#  {% if cook_list %}#}
{#    <table class="table">#}
{#      <tr>#}
{#        <th>ID</th>#}
{#        <th>Username</th>#}
{#        <th>First name</th>#}
{#        <th>Last name</th>#}
{#        <th>Years of experience</th>#}
{#        <th>Delete</th>#}
{#      </tr>#}
{#      {% for cook in cook_list %}#}
{#        <tr>#}
{#          <td>{{ cook.id }}</td>#}
{#          <td><a href="{{ cook.get_absolute_url }}">{{ cook.username }} {% if user == cook %} (Me){% endif %}</a>#}
{#          </td>#}
{#          <td>{{ cook.first_name }}</td>#}
{#          <td>{{ cook.last_name }}</td>#}
{#          <td>{{ cook.years_of_experience }}</td>#}
{#          <td>#}
{#            <a style="color: red"#}
{#               href="{% url 'restaurant:cookers-delete' pk=cook.id %}">#}
{#              Delete#}
{#            </a>#}
{#          </td>#}
{#        </tr>#}
{#      {% endfor %}#}
{##}
{#    </table>#}
{#  {% else %}#}
{#    <p>There are no cook in the service.</p>#}
{#  {% endif %}#}
{#{% endblock %}#}


{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container" style="margin-top: 20px">
    <h1 class="d-flex justify-content-between align-items-center">
      Cook List
      <a href="{% url 'restaurant:cooks-create' %}" class="btn btn-primary">
        Create
      </a>
    </h1>

    <form method="get" action="" class="navbar-search navbar-search-light form-inline mr-sm-3">
      <div class="form-group mb-0">
        <div class="input-group input-group-alternative input-group-merge">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="fas fa-search"></i></span>
          </div>
          {{ search_form|crispy }}
        </div>
      </div>
    </form>

    {% if cook_list %}
      <table class="table table-striped">
        <thead>
        <tr>
          <th>ID</th>
          <th>Username</th>
          <th>First name</th>
          <th>Last name</th>
          <th>Years of experience</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for cook in cook_list %}
          <tr>
            <td>{{ cook.id }}</td>
            <td>
              <a href="{{ cook.get_absolute_url }}">
                {{ cook.username }} {% if user == cook %} (Me) {% endif %}
              </a>
            </td>
            <td>{{ cook.first_name }}</td>
            <td>{{ cook.last_name }}</td>
            <td>{{ cook.years_of_experience }}</td>
            <td>
              <a href="{% url 'restaurant:cooks-delete' pk=cook.id %}" class="btn btn-danger btn-sm">
                Delete
              </a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>No cooks available in the service.</p>
    {% endif %}
  </div>
{% endblock %}

templates/restaurant/dish_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container" style="margin-top: 20px">
    <h1>Delete dish {{ dish.name }}?</h1>
    <form action="" method="post">
      {% csrf_token %}

      <input type="submit" value="Yes" class="btn btn-danger">
    </form>
  </div>
{% endblock %}

templates/restaurant/dish_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="container" style="margin-top: 20px">
    <h1>
      {{ dish.name }}
      <a href="{% url 'restaurant:dish-delete' pk=dish.id %}" class="btn btn-danger link-to-page">
        Delete
      </a>

      <a href="{% url 'restaurant:dish-update' pk=dish.id %}" class="btn btn-secondary link-to-page">
        Update
      </a>
    </h1>
    <p>Dish type: ({{ dish.dish_type.name }})</p>
    <h1>
      Cooks

      {% if dish in user.dishes.all %}
        <a href="{% url 'restaurant:toggle-car-assign' pk=dish.id %}" class="btn btn-danger link-to-page">
          Delete me from this dish
        </a>
      {% else %}
        <a href="{% url 'restaurant:toggle-car-assign' pk=dish.id %}" class="btn btn-success link-to-page">
          Assign me to this dish
        </a>
      {% endif %}

    </h1>
    <hr>
    <ul>
      {% for cook in dish.cooks.all %}
        <li>{{ cook.username }} ({{ cook.first_name }} {{ cook.last_name }})</li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}

templates/restaurant/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container" style="margin-top: 20px">
    <h1>{{ object|yesno:"Update,Create" }} dish</h1>
    <form action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}

      <input type="submit" value="Submit" class="btn btn-primary">
    </form>
  </div>
{% endblock %}

templates/restaurant/dish_list.html
{#{% extends "base.html" %}#}
{#{% load crispy_forms_filters %}#}
{##}
{#{% block content %}#}
{#  <h1 style="margin-top: 20px">#}
{#    Dish List#}
{#    <a href="{% url 'restaurant:dish-create' %}" class="btn btn-primary link-to-page">#}
{#      Create#}
{#    </a>#}
{#  </h1>#}
{##}
{#  <form method="get" action="" class="form-inline">#}
{#    {{ search_form|crispy }}#}
{#    <input type="submit" class="btn" style="border: 1px solid gray;" value="🔍">#}
{#  </form>#}
{##}
{#  {% if dish_list %}#}
{#    <table class="table">#}
{#      <thead>#}
{#      <tr>#}
{#        <th>ID</th>#}
{#        <th>Name</th>#}
{#        <th>Price</th>#}
{#        <th>Dish type</th>#}
{#        <th>Update</th>#}
{#        <th>Delete</th>#}
{#      </tr>#}
{#      </thead>#}
{#      <tbody>#}
{#      {% for dish in dish_list %}#}
{#        <tr>#}
{#          <td>{{ dish.id }}</td>#}
{#          <td>#}
{#            <a href="{% url 'restaurant:dish-detail' pk=dish.id %}">#}
{#              {{ dish.name }}#}
{#            </a>#}
{#          </td>#}
{#          <td>{{ dish.price }}$</td>#}
{#          <td>{{ dish.dish_type.name }}</td>#}
{#          <td>#}
{#            <a href="{% url 'restaurant:dish-update' pk=dish.id %}">#}
{#              Update#}
{#            </a>#}
{#          </td>#}
{#          <td>#}
{#            <a style="color: red"#}
{#               href="{% url 'restaurant:dish-delete' pk=dish.id %}">#}
{#              Delete#}
{#            </a>#}
{#          </td>#}
{#        </tr>#}
{#      {% endfor %}#}
{#      </tbody>#}
{#    </table>#}
{#  {% else %}#}
{#    <p>There are no dishes in the service.</p>#}
{#  {% endif %}#}
{#{% endblock %}#}

{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container" style="margin-top: 20px">
    <h1 class="d-flex justify-content-between align-items-center">
      Dish List
      <a href="{% url 'restaurant:dish-create' %}" class="btn btn-primary">
        Create
      </a>
    </h1>

    <form method="get" action="" class="navbar-search navbar-search-light form-inline mr-sm-3">
      <div class="form-group mb-0">
        <div class="input-group input-group-alternative input-group-merge">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="fas fa-search"></i></span>
          </div>
          {{ search_form|crispy }}
        </div>
      </div>
    </form>

    {% if dish_list %}
      <table class="table table-striped">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Price</th>
            <th>Dish type</th>
            <th>Update</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for dish in dish_list %}
            <tr>
              <td>{{ dish.id }}</td>
              <td>
                <a href="{% url 'restaurant:dish-detail' pk=dish.id %}">
                  {{ dish.name }}
                </a>
              </td>
              <td>{{ dish.price }}$</td>
              <td>{{ dish.dish_type.name }}</td>
              <td>
                <a href="{% url 'restaurant:dish-update' pk=dish.id %}" class="btn btn-warning btn-sm">
                  Update
                </a>
              </td>
              <td>
                <a href="{% url 'restaurant:dish-delete' pk=dish.id %}" class="btn btn-danger btn-sm">
                  Delete
                </a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>No dishes available in the service.</p>
    {% endif %}
  </div>
{% endblock %}

templates/restaurant/dish_type_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container" style="margin-top: 20px">
    <h1 class="d-flex justify-content-between align-items-center">
      Dish Type List
      <a href="{% url 'restaurant:dish-types-create' %}" class="btn btn-primary">
        Create
      </a>
    </h1>

    <form method="get" action="" class="navbar-search navbar-search-light form-inline mr-sm-3">
      <div class="form-group mb-0">
        <div class="input-group input-group-alternative input-group-merge">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="fas fa-search"></i></span>
          </div>
          {{ search_form|crispy }}
        </div>
      </div>
    </form>

    {% if dishtype_list %}
      <table class="table table-striped">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Update</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for dish_type in dishtype_list %}
            <tr>
              <td>{{ dish_type.id }}</td>
              <td>{{ dish_type.name }}</td>
              <td>
                <a href="{% url 'restaurant:dish-types-update' pk=dish_type.id %}" class="btn btn-warning btn-sm">
                  Update
                </a>
              </td>
              <td>
                <a href="{% url 'restaurant:dish-types-delete' pk=dish_type.id %}" class="btn btn-danger btn-sm">
                  Delete
                </a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>No dish types available in the service.</p>
    {% endif %}
  </div>
{% endblock %}

templates/restaurant/dishes_list.html
{#{% extends "base.html" %}#}
{#{% load crispy_forms_filters %}#}
{##}
{#{% block content %}#}
{#  <h1 style="margin-top: 20px">#}
{#    Dish List#}
{#    <a href="{% url 'restaurant:dish-create' %}" class="btn btn-primary link-to-page">#}
{#      Create#}
{#    </a>#}
{#  </h1>#}
{##}
{#  <form method="get" action="" class="form-inline">#}
{#    {{ search_form|crispy }}#}
{#    <input type="submit" class="btn" style="border: 1px solid gray;" value="🔍">#}
{#  </form>#}
{##}
{#  {% if dish_list %}#}
{#    <table class="table">#}
{#      <thead>#}
{#      <tr>#}
{#        <th>ID</th>#}
{#        <th>Name</th>#}
{#        <th>Price</th>#}
{#        <th>Dish type</th>#}
{#        <th>Update</th>#}
{#        <th>Delete</th>#}
{#      </tr>#}
{#      </thead>#}
{#      <tbody>#}
{#      {% for dish in dish_list %}#}
{#        <tr>#}
{#          <td>{{ dish.id }}</td>#}
{#          <td>#}
{#            <a href="{% url 'restaurant:dish-detail' pk=dish.id %}">#}
{#              {{ dish.name }}#}
{#            </a>#}
{#          </td>#}
{#          <td>{{ dish.price }}$</td>#}
{#          <td>{{ dish.dish_type.name }}</td>#}
{#          <td>#}
{#            <a href="{% url 'restaurant:dish-update' pk=dish.id %}">#}
{#              Update#}
{#            </a>#}
{#          </td>#}
{#          <td>#}
{#            <a style="color: red"#}
{#               href="{% url 'restaurant:dish-delete' pk=dish.id %}">#}
{#              Delete#}
{#            </a>#}
{#          </td>#}
{#        </tr>#}
{#      {% endfor %}#}
{#      </tbody>#}
{#    </table>#}
{#  {% else %}#}
{#    <p>There are no dishes in the service.</p>#}
{#  {% endif %}#}
{#{% endblock %}#}

{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container" style="margin-top: 20px">
    <h1 class="d-flex justify-content-between align-items-center">
      Dish List
      <a href="{% url 'restaurant:dish-create' %}" class="btn btn-primary">
        Create
      </a>
    </h1>

    <form method="get" action="" class="navbar-search navbar-search-light form-inline mr-sm-3">
      <div class="form-group mb-0">
        <div class="input-group input-group-alternative input-group-merge">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="fas fa-search"></i></span>
          </div>
          {{ search_form|crispy }}
        </div>
      </div>
    </form>

    {% if dish_list %}
      <table class="table table-striped">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Price</th>
            <th>Dish type</th>
            <th>Update</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for dish in dish_list %}
            <tr>
              <td>{{ dish.id }}</td>
              <td>
                <a href="{% url 'restaurant:dish-detail' pk=dish.id %}">
                  {{ dish.name }}
                </a>
              </td>
              <td>{{ dish.price }}$</td>
              <td>{{ dish.dish_type.name }}</td>
              <td>
                <a href="{% url 'restaurant:dish-update' pk=dish.id %}" class="btn btn-warning btn-sm">
                  Update
                </a>
              </td>
              <td>
                <a href="{% url 'restaurant:dish-delete' pk=dish.id %}" class="btn btn-danger btn-sm">
                  Delete
                </a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>No dishes available in the service.</p>
    {% endif %}
  </div>
{% endblock %}